"""add completion text fields

Revision ID: 0b5019afa732
Revises: 10649920866a
Create Date: 2026-05-09 12:05:06.799094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5019afa732'
down_revision: Union[str, Sequence[str], None] = '10649920866a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_contents', sa.Column('completion_kicker', sa.String(length=255), nullable=True))
    op.add_column('lesson_contents', sa.Column('completion_title', sa.String(length=500), nullable=True))
    op.add_column('lesson_contents', sa.Column('completion_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_contents', 'completion_body')
    op.drop_column('lesson_contents', 'completion_title')
    op.drop_column('lesson_contents', 'completion_kicker')
    # ### end Alembic commands ###
