"""add after text to lesson items

Revision ID: 10649920866a
Revises: 571ca2b0f3e6
Create Date: 2026-05-08 19:13:34.522542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10649920866a'
down_revision: Union[str, Sequence[str], None] = '571ca2b0f3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_items', sa.Column('after_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_items', 'after_text')
    # ### end Alembic commands ###
