"""add lesson image fields

Revision ID: 571ca2b0f3e6
Revises: 073f7d437b23
Create Date: 2026-05-07 19:31:40.375130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571ca2b0f3e6'
down_revision: Union[str, Sequence[str], None] = '073f7d437b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_contents', sa.Column('completion_image_url', sa.String(length=500), nullable=True))
    op.add_column('lesson_contents', sa.Column('completion_image_alt', sa.String(length=500), nullable=True))
    op.add_column('lesson_items', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('lesson_items', sa.Column('image_alt', sa.String(length=500), nullable=True))
    op.add_column('lesson_sections', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('lesson_sections', sa.Column('image_alt', sa.String(length=500), nullable=True))
    op.add_column('lesson_sections', sa.Column('image_position', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_sections', 'image_position')
    op.drop_column('lesson_sections', 'image_alt')
    op.drop_column('lesson_sections', 'image_url')
    op.drop_column('lesson_items', 'image_alt')
    op.drop_column('lesson_items', 'image_url')
    op.drop_column('lesson_contents', 'completion_image_alt')
    op.drop_column('lesson_contents', 'completion_image_url')
    # ### end Alembic commands ###
