"""add hero visual to lesson content

Revision ID: a8fc10a55caa
Revises: 0b5019afa732
Create Date: 2026-05-09 17:38:39.353366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fc10a55caa'
down_revision: Union[str, Sequence[str], None] = '0b5019afa732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_contents', sa.Column('hero_visual', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_contents', 'hero_visual')
    # ### end Alembic commands ###
