"""add lesson blocks

Revision ID: c403ed1a8988
Revises: a8fc10a55caa
Create Date: 2026-05-09 21:08:28.888072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c403ed1a8988'
down_revision: Union[str, Sequence[str], None] = 'a8fc10a55caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('block_key', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_blocks_id'), 'lesson_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_blocks_section_id'), 'lesson_blocks', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_blocks_section_id'), table_name='lesson_blocks')
    op.drop_index(op.f('ix_lesson_blocks_id'), table_name='lesson_blocks')
    op.drop_table('lesson_blocks')
    # ### end Alembic commands ###
