"""create lesson content tables

Revision ID: f3237d682510
Revises: ef9c97001de3
Create Date: 2026-05-02 12:30:32.082499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3237d682510'
down_revision: Union[str, Sequence[str], None] = 'ef9c97001de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('image_prompts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_contents_id'), 'lesson_contents', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_contents_lesson_id'), 'lesson_contents', ['lesson_id'], unique=True)
    op.create_table('lesson_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_content_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('paragraphs', sa.JSON(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_content_id'], ['lesson_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_sections_id'), 'lesson_sections', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_sections_lesson_content_id'), 'lesson_sections', ['lesson_content_id'], unique=False)
    op.create_table('lesson_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_items_id'), 'lesson_items', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_items_section_id'), 'lesson_items', ['section_id'], unique=False)
    op.create_table('lesson_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_tables_id'), 'lesson_tables', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_tables_section_id'), 'lesson_tables', ['section_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_tables_section_id'), table_name='lesson_tables')
    op.drop_index(op.f('ix_lesson_tables_id'), table_name='lesson_tables')
    op.drop_table('lesson_tables')
    op.drop_index(op.f('ix_lesson_items_section_id'), table_name='lesson_items')
    op.drop_index(op.f('ix_lesson_items_id'), table_name='lesson_items')
    op.drop_table('lesson_items')
    op.drop_index(op.f('ix_lesson_sections_lesson_content_id'), table_name='lesson_sections')
    op.drop_index(op.f('ix_lesson_sections_id'), table_name='lesson_sections')
    op.drop_table('lesson_sections')
    op.drop_index(op.f('ix_lesson_contents_lesson_id'), table_name='lesson_contents')
    op.drop_index(op.f('ix_lesson_contents_id'), table_name='lesson_contents')
    op.drop_table('lesson_contents')
    # ### end Alembic commands ###
